sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t slimoualha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true slimoualha/docker-react npm run test